#!/usr/bin/env python3
"""Merges new questions into questions.json. Run with: python3 add_questions.py"""
import json, re
from pathlib import Path

QUESTIONS_PATH = Path(__file__).parent.parent / "Parlance/Resources/questions.json"

def load():
    with open(QUESTIONS_PATH) as f: return json.load(f)

def save(data):
    with open(QUESTIONS_PATH, "w") as f: json.dump(data, f, indent=2)

def add(existing, mode, band, duration, raw):
    existing_texts = {q["question"].lower().strip() for q in existing if q["mode"]==mode and q["difficultyBand"]==band}
    maxid = max((int(re.search(r'_(\d+)$',q["id"]).group(1)) for q in existing if q["mode"]==mode and q["difficultyBand"]==band), default=0)
    added = 0
    for q in raw:
        if q["question"].lower().strip() in existing_texts:
            print(f"  SKIP duplicate: {q['question'][:60]}")
            continue
        maxid += 1
        existing.append({"id": f"{mode}_{band}_{maxid:03d}", "mode": mode, "difficultyBand": band,
                          "question": q["question"], "tips": q["tips"], "targetDuration": duration,
                          "difficultyNote": q["difficultyNote"]})
        existing_texts.add(q["question"].lower().strip())
        added += 1
    return added

# ── QUESTIONS DATA ────────────────────────────────────────────────────────────
NEW_QUESTIONS = {
# format: (mode, band, targetDuration): [{"question":..., "tips":[...], "difficultyNote":...}, ...]
("debate","1-2",45): [
  {"question":"Should video games be allowed in school during lunch breaks?","tips":["State your position in the first sentence","Give one concrete reason why","Acknowledge the other side briefly before closing"],"difficultyNote":"Familiar school topic, low pressure"},
  {"question":"Is it better to have one best friend than a large group of friends?","tips":["Commit to one side immediately","Use a personal example to support your point","Keep your reasoning tight and simple"],"difficultyNote":"Personal preference topic, no wrong answer"},
  {"question":"Should kids be allowed to choose their own bedtimes?","tips":["Lead with your position","Give a reason from a child's or parent's perspective","Wrap up with a one-sentence conclusion"],"difficultyNote":"Relatable everyday topic"},
  {"question":"Is it better to live in a city than in the countryside?","tips":["Pick one and stick with it","Name one specific advantage of your choice","Address one downside briefly to show balance"],"difficultyNote":"Simple lifestyle comparison"},
  {"question":"Should junk food be completely banned from school cafeterias?","tips":["State whether you agree or disagree","Use a concrete health or fairness reason","End with what should happen instead"],"difficultyNote":"Clear-cut everyday policy"},
  {"question":"Is reading books better for you than watching movies?","tips":["Commit to one side immediately","Give one cognitive or emotional benefit","Keep examples simple and relatable"],"difficultyNote":"Easy comparison, familiar context"},
  {"question":"Should children have smartphones before the age of 13?","tips":["State your position early","Use a safety or development reason","Acknowledge parents' role in the argument"],"difficultyNote":"Relatable tech debate"},
  {"question":"Should plastic bags be banned in all grocery stores?","tips":["Take a clear stance","Give one environmental or practical reason","Mention what the alternative should be"],"difficultyNote":"Simple environmental policy"},
  {"question":"Is it better to save money than to spend it on experiences?","tips":["Pick one and defend it","Use a short personal or hypothetical example","Close with the key benefit of your choice"],"difficultyNote":"Personal finance preference"},
  {"question":"Should school days be shorter than they currently are?","tips":["State your view in the opening sentence","Cite one effect on students or learning","Keep your argument focused on one main point"],"difficultyNote":"School policy, low stakes"},
  {"question":"Is it more important to be kind than to be honest?","tips":["Pick one value to defend","Use a real-life scenario to illustrate","Acknowledge that both matter before landing your point"],"difficultyNote":"Simple values debate"},
  {"question":"Should all students be required to learn a second language?","tips":["Commit to your position","Give one career or cultural benefit","Keep it to one strong argument"],"difficultyNote":"School policy, broad audience"},
  {"question":"Is it better to live alone than to have roommates?","tips":["State your preference clearly","Name one practical reason","End with the lifestyle benefit of your choice"],"difficultyNote":"Everyday lifestyle comparison"},
  {"question":"Should cars be banned from city centers?","tips":["Take a clear stance","Give one reason related to environment, safety, or convenience","Mention one trade-off to show you understand the other side"],"difficultyNote":"Simple urban policy debate"},
  {"question":"Is cooking at home better than eating at restaurants most of the time?","tips":["Commit to one side","Give one health, cost, or lifestyle reason","Close with a short personal note"],"difficultyNote":"Everyday lifestyle topic"},
  {"question":"Should physical education grades count toward your GPA?","tips":["State your position clearly","Use one reason about fairness or health","Keep the argument direct and simple"],"difficultyNote":"School fairness question"},
  {"question":"Should voting be made mandatory for all citizens?","tips":["Take a position on individual freedom vs civic duty","Give one clear reason","Acknowledge the opposing view in one sentence"],"difficultyNote":"Civic responsibility topic"},
  {"question":"Is it better to be an early riser than a night owl?","tips":["Commit to one lifestyle","Give one productivity or health benefit","Keep it personal and relatable"],"difficultyNote":"Simple lifestyle preference"},
  {"question":"Should music lessons be required in primary school?","tips":["State your stance","Give one developmental benefit or cost argument","Close with what schools should prioritize"],"difficultyNote":"School curriculum debate"},
  {"question":"Should zoos be abolished?","tips":["Pick a side","Give one reason about animal welfare or education","Acknowledge what would replace the benefit you oppose"],"difficultyNote":"Animal welfare basics"},
  {"question":"Is it better to travel with a group than to travel solo?","tips":["Commit to one style","Name one safety or enjoyment benefit","Keep examples concrete and brief"],"difficultyNote":"Personal travel preference"},
  {"question":"Should dogs be allowed in all workplaces?","tips":["State your position","Give one reason about morale, allergies, or professionalism","Close with a practical note"],"difficultyNote":"Workplace comfort question"},
  {"question":"Should public transportation be free for all riders?","tips":["Take a stance on cost versus access","Give one reason about equity or funding","Acknowledge one trade-off"],"difficultyNote":"Simple public policy"},
  {"question":"Is it better to be a specialist than a generalist in your career?","tips":["Pick one path to defend","Give one market or fulfillment reason","Keep the argument grounded in real life"],"difficultyNote":"Career path comparison"},
  {"question":"Should fast food restaurants be taxed more heavily?","tips":["State whether you support the tax or not","Give one health or economic reason","Keep your argument to one clear point"],"difficultyNote":"Simple tax/health policy"},
  {"question":"Should children be given more household responsibilities?","tips":["Take a clear stance","Give one reason about development or fairness","Close with a brief example"],"difficultyNote":"Family responsibility debate"},
  {"question":"Is technology making us less creative?","tips":["Commit to yes or no","Give one concrete example of technology helping or hurting creativity","Keep it conversational"],"difficultyNote":"Technology and creativity question"},
  {"question":"Should national parks charge entry fees?","tips":["State your position on access vs funding","Give one reason about conservation or equity","End with what the alternative might be"],"difficultyNote":"Simple environmental policy"},
  {"question":"Is it better to learn through failure than through careful planning?","tips":["Pick one approach","Give one reason about resilience or efficiency","Use a brief relatable example"],"difficultyNote":"Learning style debate"},
  {"question":"Should team sports be required for all students?","tips":["Take a clear stance","Give one benefit or reason to opt out","Acknowledge individual differences briefly"],"difficultyNote":"School activity policy"},
  {"question":"Is breakfast the most important meal of the day?","tips":["Commit to yes or no","Give one health or productivity reason","Keep it light and direct"],"difficultyNote":"Simple health claim debate"},
  {"question":"Should smartphones be banned in restaurants?","tips":["State your view on etiquette vs freedom","Give one social or experience reason","Close with a practical note"],"difficultyNote":"Everyday etiquette debate"},
  {"question":"Is it better to own pets than not to?","tips":["Pick your position","Give one benefit or responsibility argument","Keep the examples simple"],"difficultyNote":"Personal lifestyle choice"},
  {"question":"Should all schools have a dress code even if not full uniforms?","tips":["State your stance on individual expression vs community norms","Give one concrete reason","Close simply"],"difficultyNote":"School policy variation"},
  {"question":"Is watching too much TV harmful?","tips":["Take a clear position","Give one specific effect on health or time","Keep the argument focused and brief"],"difficultyNote":"Media consumption basics"},
  {"question":"Should people be allowed to bring food and drinks into movie theaters?","tips":["Pick your side","Give one reason about experience or revenue","Keep it light and fun"],"difficultyNote":"Consumer choice debate"},
  {"question":"Is it better to have fewer, higher-quality belongings than many cheap ones?","tips":["Commit to one lifestyle","Give one practical or environmental reason","Close with the key benefit"],"difficultyNote":"Simple consumer values"},
],

("debate","3-4",60): [
  {"question":"Should social media platforms be legally required to verify the age of their users?","tips":["State your position on privacy versus protection","Give one specific reason about safety or enforcement","Acknowledge the technical or civil liberties trade-off"],"difficultyNote":"Social media regulation, some nuance"},
  {"question":"Is remote work more productive than working in an office?","tips":["Commit to one side based on evidence or experience","Give two supporting reasons—one personal, one broader","Address the strongest counterpoint briefly"],"difficultyNote":"Workplace policy with real-world evidence"},
  {"question":"Should companies pay employees based on performance rather than seniority?","tips":["State your view on fairness versus incentives","Support with one workplace outcome reason","Acknowledge how seniority rewards loyalty"],"difficultyNote":"Compensation philosophy debate"},
  {"question":"Is a college degree still worth the cost in today's economy?","tips":["Take a clear stance on ROI or opportunity cost","Cite one data point or real-world trend","Acknowledge that it depends on the field before concluding"],"difficultyNote":"Education investment debate"},
  {"question":"Should fast fashion brands be held legally accountable for environmental damage?","tips":["Position yourself on regulation vs market forces","Give one environmental or labor reason","Mention enforcement challenges briefly"],"difficultyNote":"Corporate accountability debate"},
  {"question":"Is it better to specialize early in your career or stay generalist for longer?","tips":["Commit to one strategy","Give one career outcome reason","Address the risk of the path you chose"],"difficultyNote":"Career strategy, moderate complexity"},
  {"question":"Should employers have the right to check their employees' social media profiles?","tips":["State your position on privacy versus employer rights","Give one clear reason","Address the line between public and private conduct"],"difficultyNote":"Privacy and employment debate"},
  {"question":"Is standardized testing a fair measure of student potential?","tips":["Take a stance on objectivity versus limitation","Give one concrete critique or defense of the format","Acknowledge what standardized tests do or don't capture"],"difficultyNote":"Education policy with evidence"},
  {"question":"Should a four-day work week become the standard for office workers?","tips":["State your view on productivity versus structure","Give one organizational or worker wellbeing reason","Address the sectors where this may not work"],"difficultyNote":"Work culture policy debate"},
  {"question":"Is multitasking ultimately counterproductive?","tips":["Commit to yes or no with a brief rationale","Cite one cognitive or output-quality reason","Acknowledge when multitasking can be useful"],"difficultyNote":"Productivity debate with research backing"},
  {"question":"Should unpaid internships be made illegal?","tips":["State your view on access versus exploitation","Give one reason about class inequality or labor value","Acknowledge the impact on small organizations"],"difficultyNote":"Labor rights, moderate stakes"},
  {"question":"Is online learning as effective as in-person education?","tips":["Pick a position and state it clearly","Compare one specific learning outcome between formats","Address the type of learner for whom your argument is strongest"],"difficultyNote":"Education format comparison"},
  {"question":"Should cities prioritize cycling infrastructure over expanding roads?","tips":["State your position on urban planning values","Give one reason about sustainability or congestion","Acknowledge the practical challenges of one side"],"difficultyNote":"Urban mobility policy"},
  {"question":"Is it more important for companies to prioritize social impact over profit?","tips":["Commit to one priority","Give one real-world business outcome or stakeholder reason","Address the long-term sustainability of your position"],"difficultyNote":"Business ethics debate"},
  {"question":"Should gambling advertising be banned entirely?","tips":["State your view on personal freedom versus harm prevention","Give one reason about addiction or normalization","Acknowledge the revenue or freedom trade-off"],"difficultyNote":"Consumer protection debate"},
  {"question":"Should companies be required to achieve gender diversity on their boards?","tips":["Position yourself on mandate versus voluntary change","Give one reason about representation or performance","Acknowledge the implementation challenge"],"difficultyNote":"Corporate governance debate"},
  {"question":"Is cancel culture a net positive or net negative for society?","tips":["Take a clear stance on accountability versus mob dynamics","Give one concrete effect on behavior or discourse","Address the strongest counterpoint in one sentence"],"difficultyNote":"Contemporary social debate"},
  {"question":"Should sugary drinks be taxed to reduce obesity rates?","tips":["State your view on paternalism versus public health","Give one evidence-based or principled reason","Acknowledge regressive tax concerns briefly"],"difficultyNote":"Public health policy debate"},
  {"question":"Is competition in schools beneficial for students' development?","tips":["Commit to one position on motivation versus stress","Give one developmental or outcome reason","Acknowledge age-appropriate variation"],"difficultyNote":"Education philosophy debate"},
  {"question":"Should the retirement age be raised given increasing life expectancy?","tips":["State your view on fiscal sustainability versus worker wellbeing","Give one demographic or economic reason","Address the differential impact on physical versus desk jobs"],"difficultyNote":"Social policy with demographic context"},
  {"question":"Should companies be legally required to report their carbon footprint?","tips":["State your position on transparency versus regulatory burden","Give one reason about accountability or investor rights","Acknowledge enforcement complexity"],"difficultyNote":"Corporate sustainability debate"},
  {"question":"Is it better for consumers to negotiate salary than accept the first offer?","tips":["Commit to one strategy","Give one financial or cultural reason","Acknowledge when accepting quickly makes sense"],"difficultyNote":"Career negotiation debate"},
  {"question":"Should employers be required to offer mental health days as part of sick leave?","tips":["State your view on employee wellbeing versus cost","Give one productivity or retention reason","Acknowledge potential misuse concerns briefly"],"difficultyNote":"Workplace wellbeing policy"},
  {"question":"Is entrepreneurship more risky than traditional employment in the long run?","tips":["Take a clear position on risk definition","Give one financial or personal security reason","Acknowledge survivor bias or employment instability"],"difficultyNote":"Career risk comparison"},
  {"question":"Should all clothing brands be required to use sustainable materials by 2035?","tips":["State your position on regulation versus innovation","Give one environmental or cost reason","Address the timeline feasibility briefly"],"difficultyNote":"Industry sustainability mandate"},
  {"question":"Should freelancers receive the same legal benefits as full-time employees?","tips":["Position yourself on worker classification","Give one reason about equity or market flexibility","Acknowledge how this might affect freelance demand"],"difficultyNote":"Gig economy labor debate"},
  {"question":"Is brand loyalty ultimately bad for consumers?","tips":["Commit to your view on habit versus rational choice","Give one economic or quality reason","Acknowledge when brand loyalty is beneficial"],"difficultyNote":"Consumer behavior debate"},
  {"question":"Should performance reviews be replaced with continuous real-time feedback?","tips":["State your view on feedback culture","Give one reason about timeliness or bias reduction","Acknowledge the manager workload trade-off"],"difficultyNote":"Management practice debate"},
  {"question":"Should cities adopt universal basic income pilot programs?","tips":["Position yourself on the policy's merit","Give one economic or social welfare reason","Acknowledge funding or inflation concerns briefly"],"difficultyNote":"Social policy pilot debate"},
  {"question":"Is remote hiring as reliable as meeting candidates in person?","tips":["Commit to yes or no","Give one reason about bias reduction or culture fit","Acknowledge what's lost or gained in each format"],"difficultyNote":"Hiring practice debate"},
  {"question":"Should social media platforms be allowed to run political advertising?","tips":["State your view on free speech versus misinformation risk","Give one democratic or market reason","Acknowledge the line between political speech and propaganda"],"difficultyNote":"Digital democracy debate"},
  {"question":"Is it better to negotiate a raise annually than wait to be recognized?","tips":["Commit to proactive versus patient approach","Give one career advancement or relationship reason","Acknowledge when timing matters"],"difficultyNote":"Career advancement strategy"},
  {"question":"Should luxury goods be taxed more heavily than necessities?","tips":["State your view on progressive consumption tax","Give one equity or economic reason","Acknowledge consumer freedom trade-offs"],"difficultyNote":"Tax policy debate"},
  {"question":"Is working longer hours correlated with higher career success?","tips":["Commit to yes or no based on evidence or values","Give one productivity or sustainability reason","Acknowledge industry variation"],"difficultyNote":"Work ethic versus efficiency debate"},
  {"question":"Should all companies publish their internal pay scales?","tips":["State your view on pay transparency","Give one equity or market efficiency reason","Acknowledge competitive sensitivity concerns"],"difficultyNote":"Corporate transparency debate"},
  {"question":"Is it better for society to have more small businesses than large corporations?","tips":["Pick one economic structure to defend","Give one innovation, employment, or community reason","Acknowledge the efficiency trade-off"],"difficultyNote":"Economic structure debate"},
  {"question":"Should employers be required to offer paid parental leave to all parents?","tips":["State your view on equity versus cost","Give one developmental or retention reason","Acknowledge the challenge for small businesses"],"difficultyNote":"Family policy debate"},
],

("debate","5-6",75): [
  {"question":"Should artificial intelligence be regulated by a single global authority rather than individual nations?","tips":["State your position on sovereignty versus coordination","Give two reasons—one about enforcement effectiveness, one about geopolitical risk","Address the strongest objection to your view"],"difficultyNote":"Policy complexity requiring nuanced argument"},
  {"question":"Is shareholder primacy still the right organizing principle for corporations?","tips":["Take a clear stance on stakeholder theory","Support with one governance and one societal impact argument","Address the argument that profit maximization benefits society broadly"],"difficultyNote":"Corporate governance with economic theory"},
  {"question":"Should whistleblowers who expose corporate wrongdoing receive full legal immunity?","tips":["Position yourself on accountability versus legal order","Give two reasons—one about public benefit, one about procedural risk","Acknowledge how to define the scope of protection"],"difficultyNote":"Legal and ethical nuance required"},
  {"question":"Is remote-first culture better for long-term company culture than hybrid models?","tips":["Commit to a position on culture formation","Give two reasons grounded in collaboration or equity","Address the specific failure mode of remote-first you acknowledge"],"difficultyNote":"Organizational design debate"},
  {"question":"Should governments regulate the pricing of life-saving medications?","tips":["State your view on market forces versus public health","Give two reasons—one about access equity, one about R&D incentives","Address the pharmaceutical innovation trade-off directly"],"difficultyNote":"Healthcare economics with competing values"},
  {"question":"Is affirmative action an effective and fair tool for reducing workplace inequality?","tips":["Take a clear stance on remediation versus merit","Give two supporting arguments, one empirical and one principled","Address the strongest counterargument before your conclusion"],"difficultyNote":"Complex equity debate requiring evidence"},
  {"question":"Should major tech companies be broken up under existing antitrust law?","tips":["Position yourself on market concentration versus consumer benefit","Give two reasons—one about competition, one about innovation","Address the global competitiveness concern"],"difficultyNote":"Technology policy with economic depth"},
  {"question":"Is venture capital funding net positive for innovation in the long run?","tips":["Commit to your view on capital allocation efficiency","Give two reasons—one about speed, one about incentive distortion","Address whether alternatives like public R&D are adequate"],"difficultyNote":"Innovation economics debate"},
  {"question":"Should cities prioritize affordable housing mandates over market-rate luxury development?","tips":["State your view on housing as a right versus commodity","Give two reasons—one about community stability, one about supply economics","Address the fiscal revenue trade-off"],"difficultyNote":"Urban policy with economic complexity"},
  {"question":"Is the gig economy fundamentally exploitative to workers?","tips":["Take a position on flexibility versus precarity","Give two reasons—one about labor rights, one about worker preferences","Address the platform perspective on enabling entrepreneurship"],"difficultyNote":"Labor economics debate"},
  {"question":"Should all nations be legally required to adopt a carbon tax?","tips":["State your view on international climate governance","Give two reasons—one about effectiveness, one about sovereignty","Address the competitive disadvantage concern"],"difficultyNote":"Climate policy with international dimensions"},
  {"question":"Is a skills-based hiring model more equitable and effective than degree requirements?","tips":["Commit to one hiring paradigm","Give two reasons—one about access equity, one about job performance","Address signaling value and the risk of subjective skills assessment"],"difficultyNote":"HR policy with equity implications"},
  {"question":"Should social media companies be legally liable for harmful content on their platforms?","tips":["Position yourself on Section 230-style immunity","Give two reasons—one about accountability, one about free speech","Address the moderation feasibility challenge at scale"],"difficultyNote":"Platform liability debate"},
  {"question":"Is universal healthcare economically viable without significantly increasing taxes?","tips":["Take a clear stance on healthcare system design","Give two fiscal or health outcome reasons","Address the administrative efficiency argument and its limitations"],"difficultyNote":"Healthcare economics debate"},
  {"question":"Should companies be legally required to publish annual pay equity data?","tips":["State your view on transparency versus competitive sensitivity","Give two reasons—one about accountability, one about market correction","Address the limitations of pay data in isolation"],"difficultyNote":"Corporate equity reporting debate"},
  {"question":"Is ESG investing a genuine driver of change or primarily a marketing exercise?","tips":["Commit to a position on capital market activism","Give two reasons—one about portfolio pressure, one about measurement gaps","Address the greenwashing evidence directly"],"difficultyNote":"Investment ethics with evidence"},
  {"question":"Should senior corporate executives face term limits similar to political offices?","tips":["Position yourself on governance accountability","Give two reasons—one about organizational renewal, one about fiduciary risk","Address the succession and institutional knowledge challenge"],"difficultyNote":"Corporate governance debate"},
  {"question":"Is open-source software better for long-term innovation than proprietary software?","tips":["State your view on collaboration versus private investment","Give two reasons—one about access, one about incentive structure","Address the sustainability and security challenges of open source"],"difficultyNote":"Technology innovation debate"},
  {"question":"Should zero-hours contracts be banned across all industries?","tips":["Take a clear stance on labor flexibility versus security","Give two reasons—one about worker rights, one about employer constraints","Address sectors where zero-hours may serve workers' preferences"],"difficultyNote":"Labor policy with sector nuance"},
  {"question":"Should autonomous vehicles be approved for public roads before human-level safety is proven?","tips":["Position yourself on the precautionary principle versus progress","Give two reasons—one about safety benchmarks, one about net harm reduction","Address the trolley problem and legal liability questions briefly"],"difficultyNote":"Technology governance with ethics"},
  {"question":"Is merit-based pay effective at improving organizational performance long-term?","tips":["Commit to your view on incentive design","Give two reasons—one about motivation, one about collaboration and culture","Address the measurement bias and gaming problems"],"difficultyNote":"Management theory debate"},
  {"question":"Should cryptocurrency be taxed as currency rather than property?","tips":["State your view on how the tax treatment shapes behavior","Give two reasons—one about economic function, one about enforcement fairness","Address the volatility and definitional challenges"],"difficultyNote":"Financial regulation debate"},
  {"question":"Should data collected by consumer applications be treated as public infrastructure?","tips":["Position yourself on data ownership and access","Give two reasons—one about innovation, one about privacy or competition","Address the practical governance challenges"],"difficultyNote":"Data economics and rights debate"},
  {"question":"Is globalization net positive for middle-income workers in developed economies?","tips":["Take a clear stance on distributional effects","Give two reasons—one about consumer benefit, one about wage pressure","Address the retraining and transition challenge"],"difficultyNote":"Trade economics with human impact"},
  {"question":"Should the nonprofit sector face stricter accountability for the effectiveness of its capital allocation?","tips":["State your view on measuring social impact","Give two reasons—one about donor expectations, one about mission integrity","Address the difficulty of standardizing outcome measurement"],"difficultyNote":"Social sector effectiveness debate"},
  {"question":"Is the media's profit motive fundamentally incompatible with quality journalism?","tips":["Position yourself on the economics of truth","Give two reasons—one about incentive structures, one about successful counterexamples","Address the alternative funding model question"],"difficultyNote":"Media economics and democracy"},
  {"question":"Should algorithmic hiring tools be required to pass independent bias audits before deployment?","tips":["State your view on AI accountability in HR","Give two reasons—one about equity, one about accuracy","Address the audit methodology challenge"],"difficultyNote":"AI ethics in practice"},
  {"question":"Is the patent system currently helping or hurting medical innovation?","tips":["Commit to a position on intellectual property in healthcare","Give two reasons—one about incentives, one about access barriers","Address the generic drug market and compulsory licensing"],"difficultyNote":"IP policy with healthcare stakes"},
  {"question":"Should governments subsidize electric vehicle adoption through direct rebates?","tips":["State your view on the role of government in technology transitions","Give two reasons—one about speed, one about equity or efficiency","Address the regressive nature of EV incentives at high price points"],"difficultyNote":"Climate and industrial policy"},
  {"question":"Is social entrepreneurship more effective than traditional charity at solving poverty?","tips":["Position yourself on market-based versus grant-based social change","Give two reasons—one about sustainability, one about scale","Address the mission drift risk in social enterprises"],"difficultyNote":"Social impact theory debate"},
  {"question":"Should news media companies be legally required to label AI-generated content?","tips":["State your view on transparency in the information ecosystem","Give two reasons—one about audience trust, one about quality standards","Address the practical enforcement challenges"],"difficultyNote":"Media and AI policy"},
  {"question":"Is the subscription economy better for consumers than one-time purchases?","tips":["Commit to one model","Give two reasons—one about cost, one about access and lock-in","Address the cumulative cost and dependency concern"],"difficultyNote":"Consumer economics debate"},
  {"question":"Should companies be prohibited from using non-compete clauses for most employees?","tips":["State your view on labor mobility versus trade secret protection","Give two reasons—one about worker freedom, one about innovation ecosystems","Address the narrow use-case for legitimate non-competes"],"difficultyNote":"Employment law policy"},
  {"question":"Is it more effective to change corporate behavior through regulation or investor pressure?","tips":["Choose one lever of change","Give two reasons—one about speed, one about accountability","Address the capture or divestment limitations of your chosen mechanism"],"difficultyNote":"Governance mechanism debate"},
  {"question":"Should professional sports leagues be required to pay college athletes?","tips":["Position yourself on amateurism versus labor rights","Give two reasons—one about revenue sharing, one about education mission","Address Title IX equity implications briefly"],"difficultyNote":"Sports labor policy"},
  {"question":"Is it better for cities to invest in public transit over highway infrastructure?","tips":["Commit to one infrastructure priority","Give two reasons—one about climate or equity, one about economic development","Address regional variation in transit viability"],"difficultyNote":"Urban infrastructure policy"},
  {"question":"Should pharmaceutical companies be required to fund independent drug safety trials?","tips":["State your view on industry self-regulation","Give two reasons—one about bias reduction, one about cost allocation","Address the innovation funding model impact"],"difficultyNote":"Healthcare industry accountability"},
],

("debate","7-8",90): [
  {"question":"Should governments implement a universal basic income as automation displaces workers?","tips":["Make a clear thesis on UBI as a structural solution or a distraction","Support with two arguments—one about labor market dynamics, one about social cohesion","Anticipate and reframe the inflation or disincentive counterargument"],"difficultyNote":"Complex economic policy with competing evidence"},
  {"question":"Is the attention economy fundamentally incompatible with democratic deliberation?","tips":["Define the tension precisely before taking a stance","Give two reasons—one about information quality, one about polarization mechanisms","Address whether platform design reform is sufficient or structural change is required"],"difficultyNote":"Systems-level democracy and tech debate"},
  {"question":"Should nuclear energy be treated as a cornerstone of a net-zero carbon strategy?","tips":["Take a position on risk-adjusted clean energy","Give two reasons—one about baseload reliability, one about waste or proliferation","Engage directly with the cost and timeline objection"],"difficultyNote":"Energy policy with technical and ethical dimensions"},
  {"question":"Should platform companies like Uber and DoorDash be legally required to classify workers as employees?","tips":["Position yourself on worker classification","Give two arguments—one about rights and benefits, one about market design","Address the potential cost increases and worker preferences for flexibility"],"difficultyNote":"Gig economy and labor law complexity"},
  {"question":"Is meritocracy in practice a myth that legitimizes inequality?","tips":["Commit to a position on opportunity versus outcome equality","Give two reasons—one about structural barriers, one about incentive value","Address whether meritocracy as an ideal is worth preserving separately from its flawed implementation"],"difficultyNote":"Sociological debate requiring conceptual precision"},
  {"question":"Should data be treated as a public utility rather than private corporate property?","tips":["Define data ownership models clearly before arguing","Give two reasons—one about competition, one about democratic control","Address the innovation incentive and data quality maintenance concerns"],"difficultyNote":"Data governance with political economy depth"},
  {"question":"Should nations prioritize GDP growth or ecological sustainability when they conflict?","tips":["State your position on economic frameworks","Give two reasons—one about long-run viability, one about political feasibility","Address the distributional argument—who suffers most from each choice"],"difficultyNote":"Macroeconomic and environmental policy tension"},
  {"question":"Is representative democracy sufficient in the age of digital communication and complexity?","tips":["Take a position on institutional adaptation","Give two reasons—one about representation quality, one about legitimacy","Address specific reform proposals rather than leaving the critique abstract"],"difficultyNote":"Democratic theory with contemporary urgency"},
  {"question":"Should pharmaceutical companies be prohibited from patenting research funded by public grants?","tips":["Position yourself on the public-private research boundary","Give two reasons—one about access equity, one about the innovation funding model","Address the argument that patents are needed to attract private capital for development"],"difficultyNote":"Biomedical innovation and IP policy"},
  {"question":"Is the current higher education model economically unsustainable, and who should bear the cost?","tips":["Commit to a systemic position","Give two reasons—one about value delivered, one about cost allocation","Address the credential market and what replaces it"],"difficultyNote":"Education economics with structural stakes"},
  {"question":"Should national borders be open to labor migration between wealthy and developing nations?","tips":["Take a clear stance on global labor markets","Give two reasons—one about economic efficiency, one about brain drain or sovereignty","Address the domestic political and cultural integration challenges"],"difficultyNote":"Immigration and international economics"},
  {"question":"Is it ethical for companies to use behavioral psychology to drive product engagement?","tips":["Define the ethical line between design and manipulation","Give two reasons—one about consent, one about social harm","Address the market freedom and platform competition counterargument"],"difficultyNote":"Technology ethics with philosophical depth"},
  {"question":"Should AI-generated content be required to carry permanent disclosure labels?","tips":["State your position on transparency in the information ecosystem","Give two reasons—one about trust, one about content quality","Address the definitional and enforcement challenges at scale"],"difficultyNote":"AI policy with democratic implications"},
  {"question":"Is activist investing an effective or destructive check on corporate governance?","tips":["Position yourself on the function of shareholder activism","Give two reasons—one about accountability, one about short-termism risk","Address the cases where activism has created or destroyed value"],"difficultyNote":"Capital markets and governance complexity"},
  {"question":"Should governments impose a meaningful wealth tax to fund public investment?","tips":["Commit to a fiscal position","Give two reasons—one about redistribution, one about capital formation","Address capital flight and enforcement feasibility directly"],"difficultyNote":"Tax policy with economic trade-offs"},
  {"question":"Is long-term strategic thinking structurally incompatible with quarterly earnings capitalism?","tips":["Make a structural argument about capital market incentives","Give two reasons—one about governance design, one about stakeholder misalignment","Address counterexamples like Berkshire Hathaway or patient capital models"],"difficultyNote":"Corporate strategy and financial system critique"},
  {"question":"Should surveillance capitalism be regulated even if it means free services become paid?","tips":["Position yourself on the free-for-data trade-off","Give two reasons—one about consumer harm, one about market distortion","Address whether regulation will actually shift to subscription models"],"difficultyNote":"Platform economics and privacy policy"},
  {"question":"Should developing countries prioritize industrialization or leapfrog directly to sustainable development?","tips":["Commit to a development trajectory","Give two reasons—one about sovereignty and precedent, one about resource constraints","Address the funding and technology transfer question directly"],"difficultyNote":"International development policy complexity"},
  {"question":"Is intellectual property protection currently helping or inhibiting global innovation?","tips":["Take a systemic view on IP regimes","Give two reasons—one about incentive creation, one about access and diffusion barriers","Address the difference between IP in pharmaceuticals versus software versus content"],"difficultyNote":"IP economics across domains"},
  {"question":"Should private equity firms face significantly greater regulatory scrutiny?","tips":["Position yourself on capital structure and accountability","Give two reasons—one about portfolio company workers, one about systemic financial risk","Address the argument that PE improves operational efficiency"],"difficultyNote":"Financial sector regulation debate"},
  {"question":"Should political advertising be banned on social media platforms?","tips":["State your view on platform power and democracy","Give two reasons—one about micro-targeting risk, one about free speech","Address the definitional challenge of political versus issue-based advertising"],"difficultyNote":"Digital democracy policy debate"},
  {"question":"Is degrowth economics a credible policy alternative to GDP-centric governance?","tips":["Commit to a position on economic paradigm change","Give two reasons—one about ecological viability, one about political economy","Address the distributional and employment consequences of degrowth"],"difficultyNote":"Macroeconomic paradigm debate"},
  {"question":"Should facial recognition technology be banned from all public spaces?","tips":["Position yourself on security versus civil liberties","Give two reasons—one about surveillance risk, one about existing legal safeguards","Address law enforcement use cases that generate support for the technology"],"difficultyNote":"Civil liberties and technology policy"},
  {"question":"Is the nonprofit sector an effective allocator of philanthropic capital compared to government?","tips":["Take a comparative institutional stance","Give two reasons—one about accountability, one about innovation versus equity","Address the democratic legitimacy argument for public allocation"],"difficultyNote":"Social sector and governance comparison"},
  {"question":"Should gene editing be permitted for therapeutic purposes but prohibited for genetic enhancement?","tips":["Define the therapeutic versus enhancement distinction clearly","Give two reasons—one about consent, one about inequality","Address the slippery slope and definitional enforcement challenge"],"difficultyNote":"Bioethics policy with precision required"},
  {"question":"Is the free market structurally incapable of solving the housing affordability crisis alone?","tips":["Commit to a market or interventionist position","Give two reasons—one about supply incentives, one about financialization","Address the zoning and land use political economy"],"difficultyNote":"Housing economics with structural analysis"},
  {"question":"Should the United Nations Security Council veto power be reformed?","tips":["Take a position on multilateral governance","Give two reasons—one about legitimacy, one about effectiveness in modern conflicts","Address the political feasibility and veto-holder objections"],"difficultyNote":"International relations and institutional design"},
  {"question":"Is globalization reversible, and would reversing it benefit most people?","tips":["Make a structural argument about trade dependency","Give two reasons—one about economic resilience, one about geopolitical risk","Address the developing world export growth argument for globalization"],"difficultyNote":"Global economics and political economy"},
  {"question":"Should governments nationalize critical digital infrastructure like cloud platforms?","tips":["Position yourself on state versus private ownership of critical systems","Give two reasons—one about security and resilience, one about innovation","Address the efficiency and international competitiveness arguments against nationalization"],"difficultyNote":"Critical infrastructure governance debate"},
  {"question":"Is hybrid work ultimately destroying organizational culture compared to fully in-person?","tips":["Commit to a cultural model","Give two reasons—one about trust formation, one about equity and access","Address the generational and role-specific variation in hybrid effectiveness"],"difficultyNote":"Organizational culture with evidence"},
  {"question":"Should the tech sector face sector-specific regulation similar to banking and healthcare?","tips":["State your view on industry-specific versus horizontal regulation","Give two reasons—one about systemic risk, one about innovation trade-offs","Address the international regulatory arbitrage concern"],"difficultyNote":"Technology governance framework debate"},
  {"question":"Is the current international financial architecture biased against developing economies?","tips":["Take a structural position on global economic institutions","Give two reasons—one about debt dynamics, one about reserve currency power","Address the IMF conditionality and World Bank reform debates"],"difficultyNote":"International political economy depth"},
  {"question":"Should companies be required to internalize their full environmental costs through mandatory pricing?","tips":["Position yourself on externality pricing mechanisms","Give two reasons—one about market efficiency, one about political economy","Address the competitiveness and trade policy implications"],"difficultyNote":"Environmental economics policy"},
  {"question":"Is the current model of academic publishing compatible with scientific progress?","tips":["Commit to a position on open access versus commercial publishing","Give two reasons—one about access equity, one about quality control","Address the incentive structure for researchers and institutions"],"difficultyNote":"Knowledge commons policy debate"},
  {"question":"Should AI systems be granted any form of legal recognition or rights?","tips":["Define the threshold for moral or legal consideration","Give two reasons—one about current AI capabilities, one about future liability","Address the corporate personhood analogy and its limits"],"difficultyNote":"AI ethics and law, advanced framing required"},
  {"question":"Is effective altruism a coherent and sufficient framework for large-scale social change?","tips":["Position yourself on utilitarian versus structural approaches to change","Give two reasons—one about measurement, one about systemic versus individual action","Address the longtermism critique and prioritization debates within EA"],"difficultyNote":"Moral philosophy applied to social change"},
  {"question":"Should constitutional democracies impose structural limits on corporate political spending?","tips":["State your view on money as political speech","Give two reasons—one about democratic equity, one about corporate rights","Address the Citizens United reasoning and its critics"],"difficultyNote":"Constitutional law and democracy debate"},
],

("debate","9-10",120): [
  {"question":"Is liberal democracy structurally incapable of making the long-term sacrifices required for effective climate action?","tips":["Construct a precise institutional critique, not a general critique of politics","Deploy two structural arguments—one about electoral cycles, one about interest group capture","Engage with the empirical counterexamples of democratic climate legislation and their limits"],"difficultyNote":"Systemic analysis of democratic institutions"},
  {"question":"Should the concept of national sovereignty be subordinated to global governance mechanisms on existential risks?","tips":["Define the specific class of risks that justify sovereignty override","Give two reasons—one about coordination failure, one about legitimacy of global governance","Address the authoritarian capture and democratic accountability problems with global institutions"],"difficultyNote":"International relations and political philosophy"},
  {"question":"Does the proliferation of large language models constitute a genuine epistemological threat to democratic society?","tips":["Precisely define the epistemological mechanism at stake","Give two reasons—one about truth production, one about institutional trust","Address the information abundance versus quality distinction and historical analogies with past information revolutions"],"difficultyNote":"Philosophy of knowledge applied to AI"},
  {"question":"Should antitrust law be redesigned around data and attention rather than traditional price theory?","tips":["Make a conceptual argument for why traditional antitrust metrics are insufficient","Give two reasons—one about market power measurement, one about consumer harm definition","Address whether existing consumer protection law can be extended without new antitrust theory"],"difficultyNote":"Legal and economic theory debate"},
  {"question":"Is the concept of economic growth structurally incompatible with planetary boundaries in the long run?","tips":["Distinguish between GDP growth and material throughput carefully","Give two reasons—one about decoupling evidence, one about political economy of transition","Address the distributional justice of growth-versus-sustainability trade-offs in developing versus developed contexts"],"difficultyNote":"Ecological economics and development theory"},
  {"question":"Should constitutional democracies impose structural limits on market concentration in the interest of democratic equality?","tips":["Construct a theory of how economic concentration translates into political inequality","Give two reasons—one about regulatory capture, one about media and narrative control","Address the efficiency arguments for scale and the constitutional limits of economic regulation"],"difficultyNote":"Political economy and constitutional theory"},
  {"question":"Is the post-World War II international order experiencing structural collapse or adaptive evolution?","tips":["Define your unit of analysis—institutions, norms, or power distributions","Give two reasons—one about great power rivalry, one about institutional resilience","Address the difference between reform and replacement in multilateral governance"],"difficultyNote":"International relations theory and historical analysis"},
  {"question":"Does the fiduciary model of corporate governance systematically externalize social costs that markets cannot price?","tips":["Specify which externalities are structurally invisible to fiduciary reasoning","Give two reasons—one about long-horizon risks, one about non-market stakeholder harms","Address the stakeholder capitalism literature and its critics"],"difficultyNote":"Corporate law and political economy"},
  {"question":"Is representative democracy as currently practiced sufficient to govern societies defined by deep technical complexity?","tips":["Distinguish representation failures from democratic legitimacy failures","Give two reasons—one about epistemic challenges, one about temporal misalignment","Address technocracy as an alternative and its democratic legitimacy deficit"],"difficultyNote":"Democratic theory and governance design"},
  {"question":"Should the precautionary principle govern the deployment of dual-use biotechnologies?","tips":["Define what precaution requires institutionally, not just ethically","Give two reasons—one about catastrophic risk asymmetry, one about innovation cost","Address the governance vacuum between national regulation and international coordination"],"difficultyNote":"Technology governance and risk theory"},
  {"question":"Is meritocracy in tension with democracy, and if so, which should be treated as the superior organizing principle?","tips":["Precisely define meritocracy and its distributional logic","Give two reasons—one about how meritocracy selects elites, one about democratic accountability","Address whether meritocracy can be redesigned to reinforce rather than undermine democratic equality"],"difficultyNote":"Political philosophy, requires conceptual precision"},
  {"question":"Does the financialization of the economy represent a structural failure of modern capitalism or a rational evolution of capital allocation?","tips":["Define financialization specifically—FIRE sector growth, rent extraction, or shareholder primacy","Give two reasons—one about productive investment crowding out, one about systemic fragility","Address the counterargument that financialization has democratized capital access"],"difficultyNote":"Political economy and macrofinance theory"},
  {"question":"Should intellectual property regimes be fundamentally redesigned for the age of AI-generated content?","tips":["Identify specifically which IP assumptions AI challenges—authorship, originality, or training data use","Give two reasons—one about creator incentives, one about public domain and cultural commons","Address the international harmonization challenge and competitive IP races"],"difficultyNote":"IP theory and digital economy law"},
  {"question":"Is electoral democracy structurally incapable of representing the interests of future generations?","tips":["Specify the institutional mechanisms that create inter-temporal preference distortion","Give two reasons—one about discount rates in political reasoning, one about non-voter representation","Address specific institutional innovations—constitutional courts, future generations commissioners—and their limits"],"difficultyNote":"Intergenerational justice and institutional design"},
  {"question":"Should the digital commons be governed by democratic institutions rather than private platforms?","tips":["Define what commons governance means institutionally at digital scale","Give two reasons—one about information access, one about public sphere quality","Address the operational and innovation costs of removing private platform incentives"],"difficultyNote":"Political theory of digital infrastructure"},
  {"question":"Is the nation-state the appropriate unit for governing global technological risks?","tips":["Identify the specific structural mismatches between national governance and transnational technology","Give two reasons—one about enforcement gaps, one about coordination externalities","Address the alternatives—treaty regimes, multistakeholder bodies—and their accountability deficits"],"difficultyNote":"Global governance and technology policy"},
  {"question":"Does the current human rights framework adequately address harms from automated decision-making systems?","tips":["Specify which rights are structurally under-protected by current frameworks","Give two reasons—one about procedural rights, one about collective versus individual harm","Address the GDPR and algorithmic accountability literature and its limitations"],"difficultyNote":"Human rights law and AI ethics"},
  {"question":"Should longtermism as a moral philosophy be incorporated into public policy frameworks?","tips":["Define longtermism precisely and distinguish its variants","Give two reasons—one about its epistemic assumptions, one about democratic legitimacy","Address the objection that longtermism crowds out near-term suffering reduction"],"difficultyNote":"Applied moral philosophy and political theory"},
  {"question":"Is the international financial system structurally biased against developing economies in ways that perpetuate underdevelopment?","tips":["Identify the specific mechanisms—debt dynamics, reserve currency, capital flow liberalization","Give two reasons—one about policy space constraints, one about financial contagion","Address the counterargument that integration has driven growth in emerging markets"],"difficultyNote":"International political economy, deep structural analysis"},
  {"question":"Does capitalism systematically underprovide public goods, and if so, is the solution market design or political economy reform?","tips":["Define the public goods failure precisely—non-excludability, non-rivalry, or coordination failures","Give two reasons—one about mechanism design solutions, one about political economy barriers","Address why mixed-economy solutions have succeeded or failed historically"],"difficultyNote":"Economic theory and institutional analysis"},
  {"question":"Should international law evolve to hold corporations directly accountable for crimes against humanity?","tips":["Identify the specific jurisdictional and legal gaps in current corporate accountability","Give two reasons—one about deterrence, one about victim remedy","Address the state sovereignty and extraterritorial enforcement challenges"],"difficultyNote":"International law and corporate accountability"},
  {"question":"Is technological unemployment a transitional adjustment challenge or a structural threat to the labor market?","tips":["Distinguish between previous automation waves and AI-driven displacement","Give two reasons—one about task versus job displacement, one about wage polarization","Address the policy responses—retraining, UBI, working-time reduction—and their feasibility"],"difficultyNote":"Labor economics and technological change theory"},
  {"question":"Does liberal political neutrality as a governing philosophy undermine the cultural conditions required for its own reproduction?","tips":["Define the paradox of liberal neutrality precisely","Give two reasons—one about civic virtue requirements, one about pluralism's cultural preconditions","Address whether procedural liberalism can be supplemented without sliding into illiberalism"],"difficultyNote":"Political philosophy, high conceptual precision required"},
  {"question":"Should democracies treat the systematic production of disinformation as a national security threat requiring legal response?","tips":["Define disinformation operationally and distinguish it from misinformation and propaganda","Give two reasons—one about democratic integrity, one about free speech limits","Address the enforcement risk of empowering governments to define truth"],"difficultyNote":"Information security and constitutional law"},
  {"question":"Is effective multilateralism possible in a world of sharpening great power competition?","tips":["Define the structural constraints on multilateral cooperation precisely","Give two reasons—one about institutional design, one about interest divergence","Address areas where cooperation has persisted despite rivalry and explain why"],"difficultyNote":"International relations theory, high sophistication"},
  {"question":"Should AI systems that meet certain capability thresholds be subject to constitutional rights analogous to legal personhood?","tips":["Precisely define the threshold and the rights regime you're proposing or opposing","Give two reasons—one about moral status criteria, one about legal system design","Address the corporate personhood analogy, its rationale, and why AI may be categorically different"],"difficultyNote":"Legal philosophy and AI ethics, expert level"},
  {"question":"Is the concept of a rules-based international order a neutral framework or a mechanism for preserving Western hegemony?","tips":["Define rules-based order and whose rules are at issue","Give two reasons—one about institutional design bias, one about enforcement selectivity","Address the alternative governance models proposed by revisionist powers and their democratic deficits"],"difficultyNote":"International relations and postcolonial theory"},
  {"question":"Does the current structure of academic incentives systematically distort scientific knowledge production?","tips":["Identify specific structural mechanisms—publish-or-perish, replication crisis, citation gaming","Give two reasons—one about truth-seeking distortion, one about resource misallocation","Address the institutional reforms proposed and the political economy of changing academic incentives"],"difficultyNote":"Philosophy of science and institutional economics"},
  {"question":"Should genetic enhancement be legally permissible for consenting adults making autonomous choices?","tips":["Distinguish therapeutic from enhancement interventions precisely","Give two reasons—one about reproductive autonomy, one about inequality amplification","Address the collective action problem when individual rational choices produce socially harmful outcomes"],"difficultyNote":"Bioethics with political philosophy implications"},
  {"question":"Is deliberative democracy a scalable institutional model for modern pluralist societies?","tips":["Define deliberative democracy precisely and distinguish it from current electoral models","Give two reasons—one about cognitive diversity requirements, one about scale and representation","Address successful deliberative experiments and why they have not replaced representative institutions"],"difficultyNote":"Democratic theory, requires philosophical rigor"},
  {"question":"Should the international community recognize a legal duty to intervene in mass atrocity situations regardless of state consent?","tips":["Distinguish humanitarian intervention from the Responsibility to Protect framework","Give two reasons—one about norm enforcement, one about sovereignty and abuse risk","Address the Security Council paralysis and the selectivity problem in intervention decisions"],"difficultyNote":"International law and humanitarian ethics"},
  {"question":"Is financialized housing policy incompatible with housing as a social right?","tips":["Define the financialization mechanisms that convert housing into an investment asset","Give two reasons—one about price formation, one about tenure insecurity","Address the pension fund and retirement savings dimensions that complicate simple de-financialization arguments"],"difficultyNote":"Housing economics and social rights theory"},
  {"question":"Does the logic of competitive geopolitics make meaningful global climate governance structurally impossible?","tips":["Define the strategic interaction problem precisely—free-rider dynamics, relative gains, carbon leakage","Give two reasons—one about institutional design failures, one about domestic political constraints","Address the partial agreements and side payments that have enabled cooperation and whether they scale"],"difficultyNote":"International relations and climate governance theory"},
  {"question":"Should behavioral economics findings be used by governments to 'nudge' citizens toward better outcomes?","tips":["Define nudging and distinguish it from paternalism and persuasion","Give two reasons—one about autonomy and consent, one about effectiveness and equity","Address the slippery slope from nudging to manipulation and the governance accountability mechanisms needed"],"difficultyNote":"Behavioral science, ethics, and public policy"},
  {"question":"Is the regulatory capture of financial regulators by the financial industry a structural feature or a correctable failure?","tips":["Define regulatory capture operationally and distinguish it from industry expertise","Give two reasons—one about structural incentives, one about the revolving door","Address the institutional design responses—independence, civil society participation, international comparison—and their limits"],"difficultyNote":"Political economy and regulatory theory"},
  {"question":"Should cosmopolitan obligations to global poor outweigh national obligations to citizens in political theory?","tips":["Define the competing duty frameworks—special obligations, contractarianism, cosmopolitanism","Give two reasons—one about moral arbitrariness of birth, one about the preconditions for effective redistribution","Address the political stability and legitimacy requirements that favor prioritizing domestic obligations"],"difficultyNote":"Political philosophy, expert-level normative theory"},
],
}

# ── MAIN ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    data = load()
    total_added = 0
    for (mode, band, duration), questions in NEW_QUESTIONS.items():
        n = add(data, mode, band, duration, questions)
        print(f"  {mode}/{band}: added {n}")
        total_added += n
    save(data)
    print(f"\nTotal added: {total_added}")
    print(f"Total questions: {len(data)}")
